ALTER TABLE murid DROP CONSTRAINT IF EXISTS murid_pkey;
ALTER TABLE murid ADD COLUMN IF NOT EXISTS tahun_ajaran TEXT DEFAULT '2024/2025';
ALTER TABLE murid ADD PRIMARY KEY ("NISN", tahun_ajaran);

ALTER TABLE jadwal_real ADD COLUMN IF NOT EXISTS tahun_ajaran TEXT DEFAULT '2024/2025';
