-- Supabase Schema for BISMA SDN Baujeng 1

CREATE TABLE IF NOT EXISTS testimoni (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timestamp TIMESTAMPTZ DEFAULT NOW(),
  nama TEXT,
  lembaga TEXT,
  fitur TEXT,
  testimoni TEXT,
  rating INTEGER
);

CREATE TABLE IF NOT EXISTS helpdesk_config (
  key TEXT PRIMARY KEY,
  value JSONB
);

-- Insert fake konfigurasi
INSERT INTO helpdesk_config (key, value) VALUES (
  'default',
  '{
    "pie_data": [
      { "name": "Lainnya", "value": 15 },
      { "name": "SD/MI", "value": 45 },
      { "name": "SMA/SMK/MA", "value": 10 },
      { "name": "SMP/MTs", "value": 30 }
    ],
    "word_cloud": [
      { "text": "Inovatif", "count": 100 },
      { "text": "Luar biasa", "count": 80 },
      { "text": "responsive", "count": 65 },
      { "text": "Keren", "count": 55 },
      { "text": "Mudah", "count": 40 },
      { "text": "Aman", "count": 85 },
      { "text": "Lengkap", "count": 70 }
    ]
  }'
) ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;
